version: '3'

services:
  php:
    build: docker/php-fpm
    working_dir: /var/www/registry-form-app
    volumes:
      - '.:/var/www/registry-form-app'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
  webserver:
    image: 'nginx:alpine'
    working_dir: /var/www/registry-form-app
    volumes:
      - '.:/var/www/registry-form-app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT_SSH}:443"

  mysql:
    image: mysql
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - 'database_data:/var/www/registry-form-app'
#  mailer:
#    image: axllent/mailpit
#    ports:
#      - "1025"
#      - "8025"
#    environment:
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data: